
basic:
  # Login credentials for churchtools, the private key for the password database etc. are to be set via the associated environment variables
  # All users of these churchtools groups have access to the wifi
  wifi_access_groups: [194]
  # Whether we want to automatically include the assignemt groups in the wifi access groups, even if they are not specifically listed there
  include_assignment_groups_in_access_groups: True
  # The split character in usernames to request a specific vlan
  vlan_separator: "#"
  # The timeout in seconds for contacting the churchtools server
  timeout: 5
  # Path to the privateKey for encrypting the passwords in the ctpassstore backend
  path_to_private_decryption_key: /ct-radius/privateDecryptionKey.pem
  # The field name in ChurchTools person database, in which the username is stored. Leave unchanged for most instances.
  username_field_name: cmsUserId
  

vlans:
  # The default vlan to sort everybody in, if they do not have higher priority via any of the following vlan assignments
  default_vlan: 30
  # This is a dictionary which maps churchtools group ids to vlans, to which the user will be assigned. Priority is in decreasing order. If the user is a member of the first inserted group he will be assigned to this vlan and all following assignments will be ignored.
  assignments:
    71: 20
    132: 20
  # This is a dictionary which maps churchtools group ids to vlans, to which the user will be assigned only if requested. Priority is again in decreasing order.
  assignments_if_requested:
    231: 110
    77: 120
    